CREATE TABLE IF NOT EXISTS room
(
    id          UUID NOT NULL,
    name        TEXT,
    description TEXT,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS datasource
(
    id                UUID NOT NULL,
    node_id           INT  NOT NULL UNIQUE,
    name              TEXT,
    type              TEXT,
    room_id           UUID REFERENCES room (id),
    functionality_map JSONB,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS datapoint
(
    id             UUID NOT NULL,
    attribute_path TEXT NOT NULL,
    node_id        INT REFERENCES datasource (node_id),
    description    TEXT,
    type           TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS data_record
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    datapoint_id UUID REFERENCES datapoint (id),
    timestamp    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    int_value    INTEGER,
    string_value TEXT,
    PRIMARY KEY (timestamp, id)
);

SELECT create_hypertable('data_record', 'timestamp', migrate_data := TRUE)